name 'andschwa-unattended_upgrades'
version '0.1.1'
source 'git://github.com/andschwa/puppet-unattended_upgrades.git'
author 'Andrew Schwartzmeyer'
license 'MIT License'
summary 'Manage Unattended Upgrades'
description 'Installs and configures the unattended upgrades service for Ubuntu'
project_page 'https://github.com/andschwa/puppet-unattended_upgrades'
